Run delete-and-create if rebase fails
worgarside/github-config-files#146

diff --git a/.github/workflows/__create_new_release.yml b/.github/workflows/__create_new_release.yml
--- a/.github/workflows/__create_new_release.yml
+++ b/.github/workflows/__create_new_release.yml
@@ -8,6 +8,11 @@ on:
         description: The build type to use for the PR ("python", "node")
         required: false
         type: string
+      commit-build-directory:
+        description: Whether to commit (and push) the build directory
+        required: false
+        type: boolean
+        default: false
       draft-release:
         description: Whether to draft a release
         required: false
@@ -251,21 +256,72 @@ jobs:
   # ensure it is up to date with the latest changes                                   #
   # --------------------------------------------------------------------------------- #
 
+  # If the pending release is the same as the release we want to create, then rebase
+  # the existing branch to ensure it is up to date with the latest changes
+  rebase-release-branch:
+    name: Rebase Release Branch
+    runs-on: ubuntu-latest
+    needs:
+      - check-for-existing-release
+      - derive-release-branch-name
+    if: |
+      needs.derive-release-branch-name.outputs.tag != 'null' &&
+      needs.check-for-existing-release.outputs.pending-release-tag ==
+        needs.derive-release-branch-name.outputs.tag
+    env:
+      GH_TOKEN: ${{ secrets.gh-token }}
+    outputs:
+      status: ${{ steps.rebase-release-branch.outputs.status }}
+    steps:
+      - name: Clone Repo
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          ref: ${{ needs.derive-release-branch-name.outputs.branch }}
+          token: ${{ secrets.gh-token }}
+
+      - name: Rebase Release Branch
+        id: rebase-release-branch
+        run: |
+          release_branch="${{ needs.derive-release-branch-name.outputs.branch }}"
+
+          git config --global user.name "worgarside-dev"
+          git config --global user.email "worgarside.dev@gmail.com"
+
+          git checkout develop
+          git pull origin develop
+
+          git checkout "$release_branch"
+
+          if ! git rebase develop; then
+            echo "Rebase failed. Exiting."
+            echo "status=failure" >> "$GITHUB_OUTPUT"
+            exit 1
+          fi
+
+          echo "status=success" >> "$GITHUB_OUTPUT"
+
+          git push origin "$release_branch" --force
+
   # If pending-release-tag is not null, and is not the same as the release we want to
-  # create, then delete the pending release
+  # create, then delete the pending release. This also runs if `rebase-release-branch`
+  # fails, as we want to delete the pending release in that case too
   delete-pending-release:
     name: Delete Pending Release
     runs-on: ubuntu-latest
     needs:
       - check-for-existing-release
       - derive-release-branch-name
+      - rebase-release-branch
     env:
       GH_TOKEN: ${{ secrets.gh-token }}
     if: |
+      always() && !cancelled() &&
       needs.check-for-existing-release.outputs.pending-release-tag != 'null' &&
-      needs.derive-release-branch-name.outputs.tag != 'null' &&
+        needs.derive-release-branch-name.outputs.tag != 'null' &&
       needs.check-for-existing-release.outputs.pending-release-tag !=
-      needs.derive-release-branch-name.outputs.tag
+        needs.derive-release-branch-name.outputs.tag &&
+      needs.rebase-release-branch.outputs.status != 'success'
     steps:
       - name: Clone Repo
         uses: actions/checkout@v3
@@ -350,47 +406,6 @@ jobs:
           git push origin \
             ${{ needs.derive-release-branch-name.outputs.branch }}
 
-  # If the pending release is the same as the release we want to create, then rebase
-  # the existing branch to ensure it is up to date with the latest changes
-  rebase-release-branch:
-    name: Rebase Release Branch
-    runs-on: ubuntu-latest
-    needs:
-      - check-for-existing-release
-      - derive-release-branch-name
-    if: |
-      needs.derive-release-branch-name.outputs.tag != 'null' &&
-      needs.check-for-existing-release.outputs.pending-release-tag ==
-        needs.derive-release-branch-name.outputs.tag
-    env:
-      GH_TOKEN: ${{ secrets.gh-token }}
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          ref: ${{ needs.derive-release-branch-name.outputs.branch }}
-          token: ${{ secrets.gh-token }}
-
-      - name: Rebase Release Branch
-        run: |
-          release_branch="${{ needs.derive-release-branch-name.outputs.branch }}"
-
-          git config --global user.name "worgarside-dev"
-          git config --global user.email "worgarside.dev@gmail.com"
-
-          git checkout develop
-          git pull origin develop
-
-          git checkout "$release_branch"
-
-          if ! git rebase develop; then
-            echo "Rebase failed. Exiting."
-            exit 1
-          fi
-
-          git push origin "$release_branch" --force
-
   draft-release:
     if: |
       always() &&
@@ -409,6 +424,9 @@ jobs:
     with:
       base-ref-name: main
       build-type: ${{ inputs.build-type }}
+      # Only want to commit if (requested, and) the release branch was newly created
+      # yamllint disable-line rule:line-length
+      commit-build-directory: ${{ inputs.commit-build-directory == 'true' && needs.create-release-branch.result == 'success' }}
       head-ref-name: ${{ needs.derive-release-branch-name.outputs.branch }}
       node-build-directory: ${{ inputs.node-build-directory }}
       publish-to-test-pypi: ${{ inputs.publish-to-test-pypi }}
