Revert to rebasing update branch

diff --git a/.github/workflows/__create_new_release.yml b/.github/workflows/__create_new_release.yml
--- a/.github/workflows/__create_new_release.yml
+++ b/.github/workflows/__create_new_release.yml
@@ -287,10 +287,10 @@ jobs:
           git push origin \
             ${{ needs.derive-release-branch-name.outputs.release-branch }}
 
-  # If the pending release is the same as the release we want to create, then update
+  # If the pending release is the same as the release we want to create, then rebase
   # the existing branch to ensure it is up to date with the latest changes
-  update-release-branch:
-    name: Update Release Branch
+  rebase-release-branch:
+    name: Rebase Release Branch
     runs-on: ubuntu-latest
     needs:
       - check-for-existing-release
@@ -307,28 +307,24 @@ jobs:
           fetch-depth: 0
           ref: ${{ needs.derive-release-branch-name.outputs.release-branch }}
 
-      - name: Update Release Branch
-        # yamllint disable rule:line-length
+      - name: Rebase Release Branch
         run: |
           release_branch="${{ needs.derive-release-branch-name.outputs.release-branch }}"
 
           git config --global user.name "worgarside-dev"
           git config --global user.email "worgarside.dev@gmail.com"
 
-          git branch >> "$GITHUB_STEP_SUMMARY" 2>&1
+          git checkout develop
+          git pull origin develop
 
-          git fetch origin "$release_branch" >> "$GITHUB_STEP_SUMMARY" 2>&1
+          git checkout "$release_branch"
 
-          git checkout "$release_branch" >> "$GITHUB_STEP_SUMMARY" 2>&1
-
-          if git merge --no-ff develop --message "Merge \`develop\` into \`$release_branch\`"
-          then
-            git push origin "$release_branch"
-          else
-            echo "Merge resulted in conflicts. Please resolve the conflicts and commit the changes."
+          if ! git rebase develop; then
+            echo "Rebase failed. Exiting."
             exit 1
           fi
-        # yamllint enable rule:line-length
+
+          git push origin "$release_branch" --force
 
   draft-release:
     if: |
