Fix conditional check

diff --git a/.github/workflows/__manage_pr_labels.yml b/.github/workflows/__manage_pr_labels.yml
--- a/.github/workflows/__manage_pr_labels.yml
+++ b/.github/workflows/__manage_pr_labels.yml
@@ -172,16 +172,11 @@ jobs:
         run: |
           labels=$(gh pr view ${{ inputs.pr-number }} --repo ${{ github.repository }} --json labels | jq -r '.labels[].name')
 
-          if echo "$labels" | grep -qE "$(echo $REQUIRED_LABELS | tr ',' '|')"; then
+          if ! echo "$labels" | grep -qE "$(echo $REQUIRED_LABELS | tr ',' '|')"; then
             echo "No SemVer label found." >> "$GITHUB_STEP_SUMMARY"
             echo -e "Please add one of the following labels: \`$REQUIRED_LABELS\`" >> "$GITHUB_STEP_SUMMARY"
             echo -e "Found: \`$labels\`" >> "$GITHUB_STEP_SUMMARY"
             exit 1
-          else
-            echo "SemVer label found." >> "$GITHUB_STEP_SUMMARY"
-            echo -e "Found: \`$labels\`" >> "$GITHUB_STEP_SUMMARY"
-            echo $REQUIRED_LABELS | tr ',' '|' >> "$GITHUB_STEP_SUMMARY"
-            echo "$labels" | grep -qE "$(echo $REQUIRED_LABELS | tr ',' '|')" >> "$GITHUB_STEP_SUMMARY"
           fi
         # yamllint enable rule:line-length
 
