Fix label parsing

diff --git a/.github/workflows/__manage_pr_labels.yml b/.github/workflows/__manage_pr_labels.yml
--- a/.github/workflows/__manage_pr_labels.yml
+++ b/.github/workflows/__manage_pr_labels.yml
@@ -135,7 +135,7 @@ jobs:
               --jq '.labels[].name'
           )
 
-          if ! echo "$labels" | grep -qE "$(echo $REQUIRED_LABELS | tr ',' '|')"; then
+          if ! echo "$labels" | grep -qE "$(echo $REQUIRED_LABELS | tr ', ' '|')"; then
             echo "No SemVer label found." >> "${GITHUB_STEP_SUMMARY}"
             echo -e "Please add one of the following labels: \`$REQUIRED_LABELS\`" >> "${GITHUB_STEP_SUMMARY}"
             echo -e "Found: \`$labels\`" >> "${GITHUB_STEP_SUMMARY}"
